//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyID { get; set; }
        public string Customer_Name { get; set; }
        public string Employee_Name { get; set; }
        public string Insurance_Type { get; set; }
        public System.DateTime Policy_Start_Date { get; set; }
        public System.DateTime Policy_Expiration_Date { get; set; }
        public decimal Anual_Fee { get; set; }
        public string Info_About { get; set; }
        public decimal Coverage { get; set; }
    }
}
